tools:
  storm:
    path: ~/bin/storm/bin/storm
  prism:
    path: ~/bin/prism/bin/prism
  epmc:
    path: ~/bin/ePMC/epmc-standard.jar
    java: /usr/bin/java
    spot: ~/spot/bin/ltl2tgba
  modest:
    path: ~/bin/modest/bin/modest

analysis:
  timeout: 120
  valueiteration:
    epsilon:
      min: 0
      max: 0.9
      step: 0.01
  approximation:
    infinity: 100000
    precision: 0.00001